export {
    _METHODS
}

const _METHODS = {
    students: {
        GetAll: 'student.getAll',
        GetById: 'student.getByID',
        Create: 'student.create',
        Update: 'student.update',
        Delete: 'student.delete',
    },
    admin: {
        GetAll: 'admin.getAll',
        GetById: 'admin.getByID',
        Create: 'admin.create',
        Update: 'admin.update',
        Delete: 'admin.delete',
    },
    car: {
        GetAll: 'car.getAll',
        GetById: 'car.getByID',
        Create: 'car.create',
        Update: 'car.update',
        Delete: 'car.delete',
    },
    carFuel: {
        GetAll: 'carFuel.getAll',
        GetById: 'carFuel.getByID',
        Create: 'carFuel.create',
        Update: 'carFuel.update',
        Delete: 'carFuel.delete',
    },
    carMaintenance: {
        GetAll: 'carMaintenance.getAll',
        GetById: 'carMaintenance.getByID',
        Create: 'carMaintenance.create',
        Update: 'carMaintenance.update',
        Delete: 'carMaintenance.delete',
    },
    carModel: {
        GetAll: 'carModel.getAll',
        GetById: 'carModel.getByID',
        Create: 'carModel.create',
        Update: 'carModel.update',
        Delete: 'carModel.delete',
    },
    carStop: {
        GetAll: 'carStop.getAll',
        GetById: 'carStop.getByID',
        Create: 'carStop.create',
        Update: 'carStop.update',
        Delete: 'carStop.delete',
    },
    carStopTrip: {
        GetAll: 'carStopTrip.getAll',
        GetById: 'carStopTrip.getByID',
        Create: 'carStopTrip.create',
        Update: 'carStopTrip.update',
        Delete: 'carStopTrip.delete',
    },
    class: {
        GetAll: 'class.getAll',
        GetById: 'class.getByID',
        Create: 'class.create',
        Update: 'class.update',
        Delete: 'class.delete',
    },
    config: {
        GetAll: 'config.getAll',
        GetById: 'config.getByID',
        Create: 'config.create',
        Update: 'config.update',
        Delete: 'config.delete',
    },
    driver: {
        GetAll: 'driver.getAll',
        GetById: 'driver.getByID',
        Create: 'driver.create',
        Update: 'driver.update',
        Delete: 'driver.delete',
    },
    feedback: {
        GetAll: 'feedback.getAll',
        GetById: 'feedback.getByID',
        Create: 'feedback.create',
        Update: 'feedback.update',
        Delete: 'feedback.delete',
    },
    log: {
        GetAll: 'log.getAll',
        GetById: 'log.getByID',
    },
    modules: {
        GetAll: 'modules.get',
        Create: 'modules.create',
        Update: 'modules.update',
        Delete: 'modules.delete',
        GetIcons: 'modules.getIcons',
        Init: 'modules.init'
    },
    Nanny: {
        GetAll: 'Nanny.getAll',
        GetById: 'Nanny.getByID',
        Create: 'Nanny.create',
        Update: 'Nanny.update',
        Delete: 'Nanny.delete',
    },
    notification: {
        GetAll: 'notification.getAll',
        Create: 'notification.create',
        Update: 'notification.update',
        Delete: 'notification.delete',
    },
    Parrent: {
        GetAll: 'Parrent.getAll',
        GetById: 'Parrent.getByID',
        Create: 'Parrent.create',
        Update: 'Parrent.update',
        Delete: 'Parrent.delete',
    },
    ParrentRequest: {
        GetAll: 'ParrentRequest.getAll',
        GetById: 'ParrentRequest.getByID',
        Create: 'ParrentRequest.create',
        Update: 'ParrentRequest.update',
        Delete: 'ParrentRequest.delete',
    },
    route: {
        GetAll: 'route.getAll',
        GetById: 'route.getByID',
        Create: 'route.create',
        Update: 'route.update',
        Delete: 'route.delete',
    },
    school: {
        GetAll: 'school.getAll',
        GetById: 'school.getByID',
        Create: 'school.create',
        Update: 'school.update',
        Delete: 'school.delete',
    },
    studentList: {
        GetAll: 'studentList.getAll',
        GetById: 'studentList.getByID',
        Create: 'studentList.create',
        Update: 'studentList.update',
        Delete: 'studentList.delete',
    },
    studentTrip: {
        GetAll: 'studentTrip.getAll',
        GetById: 'studentTrip.getByID',
        Create: 'studentTrip.create',
        Update: 'studentTrip.update',
        Delete: 'studentTrip.delete',
    },
    task: {
        Update: 'task.update',
    },
    teacher: {
        GetAll: 'teacher.getAll',
        GetById: 'teacher.getByID',
        Create: 'teacher.create',
        Update: 'teacher.update',
        Delete: 'teacher.delete',
    },
    token: {
        GetAll: 'token.getAll',
        GetById: 'token.getByID',
        Create: 'token.create',
        Update: 'token.update',
        Delete: 'token.delete',
    },
    trip: {
        GetAll: 'trip.getAll',
        GetById: 'trip.getByID',
        Create: 'trip.create',
        Update: 'trip.update',
        Delete: 'trip.delete',
    },
    tripLocation: {
        GetAll: 'tripLocation.getAll',
        GetById: 'tripLocation.getByID',
        Create: 'tripLocation.create',
        Update: 'tripLocation.update',
        Delete: 'tripLocation.delete',
    },
    user: {
        GetAll: 'user.getAll',
        GetById: 'user.getByID',
        Create: 'user.create',
        Update: 'user.update',
        Delete: 'user.delete',
    }
}